#ifndef I2C_CONFIG_H
#define I2C_CONFIG_H

#include "i2c.h"

/* This file will be generated by the GUI */

#define I2C_SELECTED_BOARD   I2C_BOARD_STM32
#define I2C_SELECTED_BUS     1
#define I2C_SELECTED_SPEED  I2C_SPEED_STANDARD
#define I2C_OWN_ADDRESS     0x08

#endif /* I2C_CONFIG_H */
